
name: Create release
on:
  push:
    branches: [ main ]

jobs:
  os_matrix: 
    strategy:
      matrix:
        os: [ubuntu-latest, macos-15]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: rustup default 1.86.0
